<img src="https://github.com/nicholasmetherall/digital-earth-pacific-macblue-activities/blob/main/attachments/images/DE_Pacific_banner.JPG?raw=true" width="900"/>

Figure 1.1.a. Jupyter environment + Python notebooks

# Digital Earth Pacific Notebook 1 data pre-processing and postcard generation

The objective of this notebook is to pre-process geospatial data points and assign a value id for each class to enable systematic classification based on the class_id value.

##### Load libraries and functions

In [1]:
from datetime import datetime
import pandas as pd
import geopandas as gpd

##### Predefined variable for title and version
setting the date as now (which is the current processing date), and the filename for your training data.

In [29]:
date = datetime.now()
title = 'lulc'
site = 'fiji'
filename = f"{title}-{site}.geojson"

<font color='blue'>1.1. Reading the datapoints using the "read_file" function

Your code goes in the cells below. Add more cells here by clicking on the + button above.

First let's try and read your geojson datapoints in using the geopandas (gpd) library and the read_file function   

> tdata = gpd.read_file(f"training-data/{filename}")

In [30]:
tdata = gpd.read_file(f"training-data/{filename}")

Open the geojson file to see the attributes
>tdata

In [31]:
tdata

       fid ClassId     Class            SubClass                     geometry
0      1.0       2    Forest           NatForest  POINT (178.32503 -17.53472)
1      2.0       2    Forest           NatForest   POINT (178.2996 -17.53489)
2      3.0       1  Cropland           Sugarcane   POINT (177.51112 -17.5507)
3      4.0       2    Forest  SoftwoodPlantation  POINT (177.65104 -17.55029)
4      5.0       1  Cropland           Sugarcane  POINT (177.66376 -17.55024)
...    ...     ...       ...                 ...                          ...
11248  NaN       1  Cropland                None  POINT (177.73322 -17.52969)
11249  NaN       1  Cropland                None  POINT (177.73384 -17.53782)
11250  NaN       1  Cropland                None  POINT (177.73572 -17.54677)
11251  NaN       1  Cropland                None  POINT (177.72814 -17.54304)
11252  NaN       1  Cropland                None   POINT (177.6916 -17.52894)

[11253 rows x 5 columns]

In [1]:
# tdata.explore()

This script checks the Class column in the training dataset to identify the number of unique classes and display their names. 
It is used to verify that the training data was loaded correctly before running the machine learning classification process.

>print('list of', tdata['Class'].nunique(),'unique classes')

In [33]:
print('list of', tdata['Class'].nunique(),'unique classes')

list of 7 unique classes

Print the class name
> print(tdata['Class'].unique())

In [34]:
print(tdata['Class'].unique())

['Forest' 'Cropland' 'Grassland' 'Settlement' 'Bare_Other' 'Mangroves'
 'Water']

By running this block of code you can print the class names and the number of points for each classes.
> print(tdata['Class'].value_counts())

In [35]:
print(tdata['Class'].value_counts())

Class
Forest        5114
Grassland     2273
Mangroves     1756
Cropland       917
Settlement     509
Water          384
Bare_Other     300
Name: count, dtype: int64

Also, print the total number of points in this dataset
> print('total gps points',(len(tdata)))

In [36]:
print('total gps points',(len(tdata)))

total gps points 11253

Now lets define all the landuse landcover classes in the datasets in a list.
> old_categories = ['Cropland', 'Forest', 'Grassland', 'Mangroves', 'Settlement', 'Water','Bare_Other']

In [37]:
old_categories = ['Cropland', 'Forest', 'Grassland', 'Mangroves', 'Settlement', 'Water','Bare_Other']

Lets assign a code to each class based on the number of classes available in a list
> new_groups = [1, 2, 3, 4, 5, 6, 7]

In [38]:
new_groups = [1, 2, 3, 4, 5, 6, 7]

Create a mapping dictionary and store the class categories and the class code in it
> category_mapping = dict(zip(old_categories, new_groups))

In [39]:
category_mapping = dict(zip(old_categories, new_groups))

Apply mapping 
>tdata['LULC_code'] = tdata['Class'].map(category_mapping)

In [40]:
tdata['LULC_code'] = tdata['Class'].map(category_mapping)

Now lets print the class code and the number of points for each claases that is tagged to the value code. 
This particular line works by creating a new column and call it 'LULC_CODE' and set the type to integer since it will hold
value code for each classes.
>tdata['LULC_code'] = tdata['LULC_code'].astype('Int64')

In [41]:
tdata['LULC_code'] = tdata['LULC_code'].astype('Int64')

Use the value_counts function to count the number of points based on each value code.
>print(tdata['LULC_code'].value_counts())

In [42]:
print(tdata['LULC_code'].value_counts())

LULC_code
2    5114
3    2273
4    1756
1     917
5     509
6     384
7     300
Name: count, dtype: Int64

printing the length of the dataset or the total number of points in the dataset
>len(tdata)

In [43]:
len(tdata)

11253

This line is more like an accuracy assessment test to test any inaccuracy in the dataset in terms of mislabelling. This just basically show the cross-tab of class and code to inspect inaccuracy. 

>print("Cross-tab of LULC_class vs LULC_code (counts):")

>ct = pd.crosstab(tdata['Class'], tdata['LULC_code'])

>display(ct)

In [44]:
print("Cross-tab of LULC_class vs LULC_code (counts):")

ct = pd.crosstab(tdata['Class'], tdata['LULC_code'])

display(ct)

Cross-tab of LULC_class vs LULC_code (counts):

LULC_code     1     2     3     4    5    6    7
Class
Bare_Other    0     0     0     0    0    0  300
Cropland    917     0     0     0    0    0    0
Forest        0  5114     0     0    0    0    0
Grassland     0     0  2273     0    0    0    0
Mangroves     0     0     0  1756    0    0    0
Settlement    0     0     0     0  509    0    0
Water         0     0     0     0    0  384    0

Explore the dataset using the explore function based on the attributes you want to visualize 
> tdata.explore(column='Class')

In [2]:
# tdata.explore(column='Class')

Again by running this block of code you can print the class code and the number of points for each classes.
> print(tdata['LULC_code'].value_counts())

In [46]:
print(tdata['LULC_code'].value_counts())

LULC_code
2    5114
3    2273
4    1756
1     917
5     509
6     384
7     300
Name: count, dtype: Int64

Also, print the total number of points in this dataset
> print('total gps points',(len(tdata)))

In [47]:
print('total gps points',(len(tdata)))

total gps points 11253

Export the pre-processed dataset in a postcard.geojson format
>tdata.to_file("training-data/"f"{version}_postcard_4.geojson")

In [49]:
tdata.to_file("training-data/"f"{site}-tdata.geojson")